example/gs_config_nested_cv.yml
pytest/metrics/test_metrics.py
src/ml_gym/batching/batch.py
src/ml_gym/blueprints/constructables.py
src/ml_gym/gym/evaluator.py
src/ml_gym/gym/jobs.py
src/ml_gym/gym/trainer.py
src/ml_gym/loss_functions/loss_factory.py
src/ml_gym/loss_functions/loss_functions.py
src/ml_gym/loss_functions/multi_term_loss_functions.py

* Improved the GPU footprint and RAM footprint

Gpu memory footprint reduction

---

src/ml_gym/batching/batch.py
src/ml_gym/gym/jobs.py

Training state and final model are now stored on disc

Persistency GymJobLite fix

---

pytest/optimizers/test_optimizers.py
src/ml_gym/blueprints/constructables.py
src/ml_gym/gym/jobs.py
src/ml_gym/gym/trainer.py
src/ml_gym/optimizers/optimizer.py
src/ml_gym/optimizers/optimizer_factory.py
src/ml_gym/persistency/io.py

* implemented a wrapper around the pytorch optimizer

Optimizer refactoring

---

pytest/data_handling/test_dataset_loader.py
src/ml_gym/blueprints/constructables.py
src/ml_gym/data_handling/dataset_loader.py

made dataloader target label position configurable

Dataloader refactoring

---

pytest/loss_functions/test_loss_functions.py
pytest/optimizers/test_optimizers.py

fixed the unpassed test module for test_bce_with_logits_loss: test data dimension unmatches

fix the dimension unmatch bug for test_bce_with_logits_loss

---

src/ml_gym/blueprints/component_factory.py
src/ml_gym/blueprints/constructables.py
src/ml_gym/optimizers/optimizer.py

Implemented a new Optimizer which bundles multiple optimizers into a single class. This comes in handy when, e.g., wanting to optimize the components of an ensemble independently and with different hyper parameters.

OptimizerBundle

---

pytest/registries/test_registries.py
src/ml_gym/registries/class_registry.py

test registry

---

pytest/multiprocessing/mocked_func.py
pytest/multiprocessing/test_job.py
pytest/multiprocessing/test_pool.py
pytest/multiprocessing/test_worker.py

test module for multiprocessing module

Br76 test multiprocessing

---

example/conv_net_blueprint.py
src/ml_gym/backend/README.md
src/ml_gym/backend/streaming/client.py
src/ml_gym/backend/streaming/websocket_server.py
src/ml_gym/blueprints/blue_prints.py
src/ml_gym/frontend/dashboard/src/App.tsx
src/ml_gym/frontend/dashboard/src/app/datatypes.ts
src/ml_gym/frontend/dashboard/src/app/store.tsx
src/ml_gym/frontend/dashboard/src/features/experimentConfig/experimentConfigSlice.tsx
src/ml_gym/gym/gym.py
src/ml_gym/gym/jobs.py
src/ml_gym/multiprocessing/job.py
src/ml_gym/persistency/logging.py
src/setup.py

within the Gym.py we log now the experiment configuration to the websocket server

Experiment config logging

---

example/conv_net_blueprint.py
example/train_gs_mnist_conv_net_websocket.sh
src/ml_gym/backend/README.md
src/ml_gym/backend/messaging/event_storage.py
src/ml_gym/backend/streaming/client.py
src/ml_gym/backend/streaming/websocket_server.py
src/ml_gym/blueprints/blue_prints.py
src/ml_gym/frontend/dashboard/src/App.tsx
src/ml_gym/frontend/dashboard/src/app/datatypes.ts
src/ml_gym/frontend/dashboard/src/app/store.tsx
src/ml_gym/frontend/dashboard/src/features/experimentConfig/experimentConfigSlice.tsx
src/ml_gym/gym/gym.py
src/ml_gym/gym/jobs.py
src/ml_gym/multiprocessing/job.py
src/ml_gym/persistency/logging.py
src/setup.py

* refactored interfaces of event storage
* implemented `DiscEventStorage` for persistent event sourcing

Persistent event storage

---

example/conv_net_blueprint.py
example/run.py
example/train_gs_mnist_conv_net_websocket.sh
src/ml_gym/backend/README.md
src/ml_gym/backend/messaging/event_storage.py
src/ml_gym/backend/streaming/client.py
src/ml_gym/backend/streaming/websocket_server.py
src/ml_gym/backend/streaming/websocket_server_dummy.py
src/ml_gym/blueprints/blue_prints.py
src/ml_gym/frontend/dashboard/README.md
src/ml_gym/frontend/dashboard/src/App.tsx
src/ml_gym/frontend/dashboard/src/app/datatypes.ts
src/ml_gym/frontend/dashboard/src/app/store.tsx
src/ml_gym/frontend/dashboard/src/features/experimentConfig/experimentConfigSlice.tsx
src/ml_gym/frontend/dashboard/src/routes/flow_board.tsx
src/ml_gym/frontend/dashboard/src/template/template.css
src/ml_gym/gym/evaluator.py
src/ml_gym/gym/gym.py
src/ml_gym/gym/jobs.py
src/ml_gym/gym/trainer.py
src/ml_gym/multiprocessing/job.py
src/ml_gym/multiprocessing/pool.py
src/ml_gym/persistency/logging.py
src/ml_gym/starter.py
src/ml_gym/validation/cross_validation.py
src/ml_gym/validation/gs_validator.py
src/ml_gym/validation/nested_cross_validation.py
src/ml_gym/validation/validator_factory.py
src/setup.py

* removed the dashify logging functionality
* removed model, optimizer, stateful component logging (@PriyaTomar this still needs to be integrated into the new API)
* removed std output logging
* removed dashify data class `experiment_info`, an experiment is now identified via `grid_search_id` (timestamp) and `experiment_id` (int)
* improved the callback functionality for model_status and evaluation_status within `trainer` and `evaluator`
* removed gym job light
* removed `keep_interim_results`; needs to be replaced by the checkpointing strategy (@PriyaTomar)
* minor changes to the websocket API (as documented in the README)

Logging callbacks refactoring

---

example/conv_net_blueprint.py
example/run.py
src/ml_gym/blueprints/blue_prints.py
src/ml_gym/gym/jobs.py
src/ml_gym/modes.py
src/ml_gym/persistency/io.py
src/ml_gym/starter.py
src/ml_gym/validation/cross_validation.py
src/ml_gym/validation/gs_validator.py
src/ml_gym/validation/nested_cross_validation.py
src/ml_gym/validation/validator_factory.py

implemented warm start

---

example/conv_net_blueprint.py
example/grid_search/grid_search_checkpoint.yaml
example/grid_search/single_model_config.yml
example/run.py
src/ml_board/README.md
src/ml_board/backend/restful_api/restful_api_server.py
src/ml_gym/blueprints/blue_prints.py
src/ml_gym/blueprints/component_factory.py
src/ml_gym/blueprints/constructables.py
src/ml_gym/checkpoint/checkpoint.py
src/ml_gym/checkpoint/checkpoint_factory.py
src/ml_gym/early_stopping/early_stopping_strategies.py
src/ml_gym/error_handling/exception.py
src/ml_gym/gym/gym.py
src/ml_gym/gym/jobs.py
src/ml_gym/io/config_parser.py
src/ml_gym/modes.py
src/ml_gym/multiprocessing/job.py
src/ml_gym/multiprocessing/pool.py
src/ml_gym/persistency/io.py
src/ml_gym/persistency/logging.py
src/ml_gym/starter.py
src/ml_gym/util/util.py
src/ml_gym/validation/cross_validation.py
src/ml_gym/validation/gs_validator.py
src/ml_gym/validation/nested_cross_validation.py
src/ml_gym/validation/validator.py
src/ml_gym/validation/validator_factory.py
src/setup.py

**Added** :checkpoint Interface, Factory, and Registry Constructable. 
**Current_status**: Error in execution because of MLGym config eg constructable and yaml config.

added basic model checkpoint startegy

---

src/ml_gym/persistency/logging.py

Switched over to pytorch.save for model checkpoint creation.

replaced pickle.dumps with torch.save

---

src/ml_board/frontend/Dashboard/src/app/App.tsx
src/ml_board/frontend/Dashboard/src/components/graphs/Graph.tsx
src/ml_board/frontend/Dashboard/src/redux/charts/chartsSlice.ts
src/ml_board/frontend/Dashboard/src/redux/status/statusSlice.ts
src/ml_board/frontend/Dashboard/src/redux/table/tableSlice.ts
src/ml_board/frontend/Dashboard/src/worker_socket/DataTypes.ts
src/ml_board/frontend/Dashboard/src/worker_socket/MainThreadCallbacks.ts
src/ml_board/frontend/Dashboard/src/worker_socket/WorkerSocket.ts
src/ml_board/frontend/Dashboard/src/worker_socket/event_handlers/EvaluationResultHandler.ts

* loop extraction into a function
* separate each graph inside graphs
* reformated handling evaluation results
* clearning (renaming and commeting out)
* added colors back
* Buffer Messages Done
* cleaning up
* the forgotten updates in the PR #154 for issue #152
* initial fix to the buffered window approch, next is to avoid the big loop in the chartSlice
* changed the hyperparameter of the BufferWindow and tried some chartjs optimization
---------

Buffer Messages Done (#155)

---

.gitignore
example/bert/bert_lm_blueprint.py
example/bert/bert_lm_config.yml
example/bert/bert_model.py
example/bert/mlm_loss_function.py
example/bert/run.py
example/bert/train_bert.sh
src/ml_gym/blueprints/component_factory.py
src/ml_gym/blueprints/constructables.py
src/ml_gym/data_handling/dataset_loader.py
src/ml_gym/gym/evaluator.py
src/ml_gym/gym/trainer.py
src/setup.py

Implemented the Bert language model as a getting started example for MLgym.

Bert lm example

---

src/ml_board/README.md
src/ml_board/backend/restful_api/data_access.py
src/ml_board/backend/restful_api/restful_api_server.py

Now folders are deleted in two ways:
1) For DELETE /checkpoints/<grid_search_id>/<experiment_id>/<checkpoint_id> delete folder.
2) For DELETE /checkpoints/<grid_search_id><experiment_id>/<checkpoint_id>/<checkpoint_resource> delete folder if folder is empty.

Mlgym#163 del check emp fold

---

src/ml_board/README.md
src/ml_board/backend/restful_api/data_access.py
src/ml_board/backend/restful_api/restful_api_server.py
src/ml_gym/cmd_entrypoint/cmd.py
src/ml_gym/error_handling/exception.py
src/ml_gym/persistency/io.py
src/ml_gym/util/util.py

Added run_config to event storage using existing API functionality.
New API to fetch system info (CPU & GPU):
_/system-info_
Response:
{
"platform": <Operating system>,
"platform-release": <OS version>,
"architecture": <system architecture ex: AMD64>,
"processor": <processor name>,
"ram": <ram in GB>,
"CUDNN_version":<cudnn version>,
"num_cuda_device": <number of cuda devices>,
"cuda_device_list": [
{
"name": <name of GPU>,
"multi_proc_count": <Processor count of GPU>,
"total_memory": <Total GPU memory in GB>
}
]
}

Mlgym#193 sys info endpoint

---

README.md
example/bert/run_config.yml
example/cnn_ddp/run_config.yml
example/grid_search_example/run_config.yml
src/ml_board/backend/restful_api/data_access.py
src/ml_board/backend/restful_api/restful_api_server.py
src/ml_gym/blueprints/blue_prints.py
src/ml_gym/cmd_entrypoint/cmd.py
src/ml_gym/gym/gym.py

~~1. The README has not been updated with new args to be used to run run.py~~
2. Code refactoring is missing new code comments and documentation. (Incomplete need to wait till another pull request is merged)
~~3. The gs_config_path in the mlgym\example\grid_search_example\run_config configuration file is hard coded and has not been changed to the global path.~~

Mlgym#174 docum

---

README.md
example/bert/run_config.yml
example/cnn_ddp/run_config.yml
example/grid_search_example/run_config.yml
src/ml_board/backend/restful_api/data_access.py
src/ml_board/backend/restful_api/restful_api_server.py
src/ml_gym/cmd_entrypoint/cmd.py
src/ml_gym/gym/gym.py

Revert "Mlgym#174 docum"

---

src/ml_board/frontend/Dashboard/src/redux/charts/chartsSlice.ts

removed the includes O(n) in the chartsSlice, now accesss O(1)

---

src/ml_gym/util/util.py

Not too many changes. Fixed bugs and added new information.

Merge mlgym#222-gpu-bug

---

src/ml_board/README.md
src/ml_board/backend/restful_api/data_access.py
src/ml_board/backend/restful_api/restful_api_server.py
src/ml_gym/cmd_entrypoint/cmd.py
src/ml_gym/error_handling/exception.py
src/ml_gym/gym/gym_jobs/gym_job.py
src/ml_gym/gym/gym_jobs/standard_gym_job.py
src/ml_gym/util/util.py

New refinements and updates as requested in pull request #244  and closes #223 
Notes:
1) Added pipeline details in the model card with some beautification in JSON.
2) Creation of the model card is switched it will not be created during the start but when API is called.
3) Fixed loading of pickle files so it fixes warm starts.
4) Kept dataset details with modifications which now can retrieve info irrespective of the key name.
5) New business logic is introduced to use information from the model from the last checkpoint while creating the model card.

Mlgym#223 model card
